# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [5]:
import pandas as pd
import numpy as np

insurance_df1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

print(insurance_df1.info())
print()
insurance_df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB
None

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [3]:
insurance_df2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")

print(insurance_df2.info())
print()
insurance_df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    object
 1   ST                         996 non-null    object
 2   GENDER                     991 non-null    object
 3   Education                  996 non-null    object
 4   Customer Lifetime Value    992 non-null    object
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    object
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    object
 10  Vehicle Class              996 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 85.7+ KB
None

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [4]:
insurance_df3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

print(insurance_df3.info())
print()
insurance_df3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   object
 1   State                      7070 non-null   object
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   object
 4   Gender                     7070 non-null   object
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   object
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB
None

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [7]:
# Combining all dataframes in one called "all_insurance_df"

all_insurance_df = pd.concat([insurance_df1, insurance_df2, insurance_df3], axis=0, ignore_index=True)
print(all_insurance_df.info())
print()
all_insurance_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   object
 1   ST                         2067 non-null   object
 2   GENDER                     1945 non-null   object
 3   Education                  9137 non-null   object
 4   Customer Lifetime Value    9130 non-null   object
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   object
 8   Policy Type                9137 non-null   object
 9   Vehicle Class              9137 non-null   object
 10  Total Claim Amount         9137 non-null   float64
 11  State                      7070 non-null   object
 12  Gender                     7070 non-null   object
dtypes: float64(3), object(10)
memory usage: 1.2+ MB
None

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount,State,Gender
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,NaN,NaN
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,NaN,NaN
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,NaN,NaN
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,NaN,NaN
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,NaN,NaN

In [9]:
all_insurance_df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount', 'State',
       'Gender'],
      dtype='object')

In [11]:
# Cleaning columns name and dropping dupplicated columns

all_insurance_df=all_insurance_df.rename(columns={
        "Customer": "customer",
        "ST": "state",
        "GENDER": "gender",
        "Education": "education",
        "Customer Lifetime Value": "customer_lifetime_value",
        "Income": "income",
        "Monthly Premium Auto": "monthly_premium_auto",
        "Number of Open Complaints": "number_of_open_complaints",
        "Policy Type": "policy_type",
        "Vehicle Class": "vehicle_class", 
        "Total Claim Amount": "total_claim_amount",
    })

all_insurance_df
all_insurance_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount', 'State',
       'Gender'],
      dtype='object')

In [13]:
all_insurance_df = all_insurance_df.drop(['State', 'Gender'], axis=1)
all_insurance_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [14]:
# Cleaning invalid values respecting the previous lav directions

all_insurance_df['gender'] = (
    all_insurance_df['gender']
    .str.lower()
    .replace({
        'f': 'F',
        'female': 'F',
        'femal': 'F',
        'm': 'M',
        'male': 'M'
    })
)

all_insurance_df['gender'].unique()

array([nan, 'F', 'M'], dtype=object)

In [15]:
all_insurance_df['state'] = all_insurance_df['state'].replace({
    'AZ': 'Arizona',
    'Cali': 'California',
    'WA': 'Washington'
})

all_insurance_df['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [16]:
all_insurance_df['education'] = all_insurance_df['education'].replace({
    'Bachelors': 'Bachelor'
})

all_insurance_df['education'].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [17]:
all_insurance_df['customer_lifetime_value'] = (
    all_insurance_df['customer_lifetime_value']
    .str.replace('%', '', regex=False)
)

all_insurance_df['customer_lifetime_value'].unique()

array([nan, '697953.59', '1288743.17', ..., '568964.41', '368672.38',
       '399258.39'], shape=(1924,), dtype=object)

In [18]:
all_insurance_df['vehicle_class'] = all_insurance_df['vehicle_class'].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

all_insurance_df['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

In [19]:
# Formatting data types
#Customer lifetime value should be numeric

all_insurance_df['customer_lifetime_value'] = (
    all_insurance_df['customer_lifetime_value']
    .str.replace('%', '', regex=False)
    .astype(float)
)

all_insurance_df['customer_lifetime_value'].sample

<bound method NDFrame.sample of 0               NaN
1         697953.59
2        1288743.17
3         764586.18
4         536307.65
            ...
12069           NaN
12070           NaN
12071           NaN
12072           NaN
12073           NaN
Name: customer_lifetime_value, Length: 12074, dtype: float64>

In [21]:
# Number of open complaints has an incorrect format. 
# Look at the different values it takes with unique() and take the middle value

all_insurance_df['number_of_open_complaints'] = (
    all_insurance_df['number_of_open_complaints']
    .str.split('/')
    .str[1]
    .astype(float)
)

all_insurance_df['number_of_open_complaints'].sample

<bound method NDFrame.sample of 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
12069    NaN
12070    NaN
12071    NaN
12072    NaN
12073    NaN
Name: number_of_open_complaints, Length: 12074, dtype: float64>

In [22]:
# Dealing with Null Values

all_insurance_df[all_insurance_df.isnull().any(axis=1)]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
11,VQ65197,California,NaN,College,819719.71,0.0,110.0,0.0,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70,77026.0,110.0,2.0,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89,99845.0,110.0,1.0,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17,83689.0,70.0,2.0,Corporate Auto,Four-Door Car,307.139132
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,NaN,NaN,Bachelor,NaN,71941.0,73.0,NaN,Personal Auto,Four-Door Car,198.234764
12070,PK87824,NaN,NaN,College,NaN,21604.0,79.0,NaN,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,NaN,NaN,Bachelor,NaN,0.0,85.0,NaN,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,NaN,NaN,College,NaN,21941.0,96.0,NaN,Personal Auto,Four-Door Car,691.200000
12073,Y167826,NaN,NaN,College,NaN,0.0,77.0,NaN,Corporate Auto,Two-Door Car,369.600000

In [24]:
all_insurance_df.columns[all_insurance_df.isnull().any()]

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [28]:
all_insurance_df["gender"].sample(20)

7161     NaN
6927     NaN
5758     NaN
2205     NaN
8228     NaN
7325     NaN
5957     NaN
11165    NaN
3350     NaN
5448     NaN
114        F
3751     NaN
6889     NaN
11537    NaN
5935     NaN
5849     NaN
10540    NaN
1186     NaN
9310     NaN
4719       M
Name: gender, dtype: object

In [29]:
all_insurance_df.isnull()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
12069,False,True,True,False,True,False,False,True,False,False,False
12070,False,True,True,False,True,False,False,True,False,False,False
12071,False,True,True,False,True,False,False,True,False,False,False
12072,False,True,True,False,True,False,False,True,False,False,False
12073,False,True,True,False,True,False,False,True,False,False,False

In [33]:
# Preencher Null Values por Unknown nas colunas de texto

cols_categoricas = all_insurance_df.select_dtypes(include="object").columns
all_insurance_df[cols_categoricas] = all_insurance_df[cols_categoricas].fillna("Unknown")

cols_categoricas.isnull()

array([False, False, False, False, False, False])

In [35]:
all_insurance_df.isnull().sum()

customer                         0
state                            0
gender                           0
education                        0
customer_lifetime_value      10014
income                        2937
monthly_premium_auto          2937
number_of_open_complaints    10007
policy_type                      0
vehicle_class                    0
total_claim_amount            2937
dtype: int64

In [36]:
# "customer_lifetime_value" and "number_of_open_complaints" have a huge number of null values
# in this case, my decision is to drop both columns

all_insurance_df = all_insurance_df.drop(['customer_lifetime_value', 'number_of_open_complaints'], axis=1)
all_insurance_df.columns

Index(['customer', 'state', 'gender', 'education', 'income',
       'monthly_premium_auto', 'policy_type', 'vehicle_class',
       'total_claim_amount'],
      dtype='object')

In [37]:
# For "income", "monthly_premium_auto" and "total_claim_amount", we will fill with the mean value

cols_numericas = all_insurance_df.select_dtypes(include="number").columns
all_insurance_df[cols_numericas] = all_insurance_df[cols_numericas].fillna(
    all_insurance_df[cols_numericas].median()
)

cols_numericas.isnull()

array([False, False, False])

In [38]:
#Done!!
all_insurance_df.isnull().sum()

customer                0
state                   0
gender                  0
education               0
income                  0
monthly_premium_auto    0
policy_type             0
vehicle_class           0
total_claim_amount      0
dtype: int64

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [48]:
import pandas as pd
import numpy as np

mkt_insurance_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")

print(mkt_insurance_df.info())
print()
mkt_insurance_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB
None

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [53]:
mkt_insurance_df.groupby("sales_channel")["monthly_premium_auto"].sum()

sales_channel
Agent          386335
Branch         280953
Call Center    197970
Web            151511
Name: monthly_premium_auto, dtype: int64

In [54]:
pivot_revenue = (
    mkt_insurance_df.pivot_table(
        values="monthly_premium_auto",
        index="sales_channel",
        aggfunc="sum"
    )
    .round(2)
)

pivot_revenue

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [55]:
pivot_average = (
    mkt_insurance_df.pivot_table(
        values="customer_lifetime_value",
        index="gender",
        columns="education",
        aggfunc="mean"
    )
    .round(2)
)

pivot_average

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [57]:
complaints_summary = (
    mkt_insurance_df
        .groupby(["policy_type", "month"])["number_of_open_complaints"]
        .count()
        .reset_index()
)

complaints_summary

      policy_type  month  number_of_open_complaints
0  Corporate Auto      1                       1252
1  Corporate Auto      2                       1089
2   Personal Auto      1                       4329
3   Personal Auto      2                       3799
4    Special Auto      1                        237
5    Special Auto      2                        204